# -*- coding: utf-8 -*-
"""COVID-19 Xray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycsXylKFymKPy2N1RIrd3pr15NVDkeQn
"""

!pip install -U keras

import os
os.environ['KAGGLE_USERNAME'] = "rajanpuri" # username from the json file
os.environ['KAGGLE_KEY'] = "bf4e2652a89f13d502d899a57f88e717" # key from the json file
!kaggle datasets download -d khoongweihao/covid19-xray-dataset-train-test-sets # api copied from kaggle

ls

!unzip covid19-xray-dataset-train-test-sets.zip

ls

from keras.preprocessing.image import ImageDataGenerator
train=ImageDataGenerator(rescale=1/255.0,
                         rotation_range=20,
                         shear_range=0.4,
                         zoom_range=0.1,
                        horizontal_flip=True)
training=train.flow_from_directory(
    "xray_dataset_covid19/train",
    target_size=(150,150),
    class_mode="categorical"
)
testing=ImageDataGenerator(rescale=1/255.0)
testing=train.flow_from_directory(
    "xray_dataset_covid19/test",
    target_size=(150,150),
    class_mode="categorical"
)

from keras.preprocessing import image
for i in os.listdir("xray_dataset_covid19/train/NORMAL"):
  x=os.path.join("xray_dataset_covid19/train/NORMAL",i)
  img=image.load_img(x)
  img=image.img_to_array(img)/255.0
  plt.imshow(img)
  plt.axis("off")
  plt.show()

from keras.models import Model,Sequential
from keras.layers import *

model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(150,150,3)))

model.add(MaxPool2D(2,2))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))

model.add(Flatten())

model.add(Dense(2,activation='softmax'))
model.summary()

from keras.optimizers import Adam
model.compile(optimizer="Adam",loss="binary_crossentropy",metrics=['accuracy'])

his=model.fit_generator(training,epochs=5)

import matplotlib.pyplot as plt
plt.plot(his.history['accuracy'])
plt.plot(his.history['loss'])
plt.show()

model.evaluate(testing)

